### ISSUE TITLE
Implementation of Dynamic Grapsh in LibreNMS is not working on Safari 13.0.3

### ISSUE THREAD

**Issue by jozefrebjak** [oetiker/RrdGraphJS#6]
Hello, is there an issue with Dynamic graphs with newest SAFARI 13.0.3 on MacOS Catalina. There is an implementation of Dynamic Graphs in LibreNMS and for me on newest macos it is not working. There is a video: https://www.youtube.com/watch?v=YqBohn5eNJQ&feature=youtu.be Please take a look. Thank you.

**Comment by oetiker** [comment]
I guess librenms is not using my library ... try this demo https://tobi.oetiker.ch/smokenav/

**Comment by jozefrebjak** [comment]
@oetiker this is working for me. It's doesn't work only in LibreNMS. I think that they need to update something to get it working. It worked for me in safari too, but on previous version of MacOS and also Safari. In chrome it's working but in safari 13.0.3 not.

**Comment by jozefrebjak** [comment]
@oetiker here is the implementation of your code https://github.com/librenms/librenms/pull/9087
