### ISSUE TITLE
Implementaiton questions

### ISSUE THREAD

**Issue by pablos-here** [oetiker/RrdGraphJS#9]
Hi,

I have a few questions that I hope you may answer.  :)

I'd like to inject some life into my RRD graphs.  I've been collecting data for +10 years and I'd like to be able to make the static graphs more ... lively.  :)

1. Is the project abandoned or at a point that it is usable?
2. If I look at the sample HTML (excerpt below), I believe that **graphA** is a server-side application that will write to stdout the results of an `rrdtool graph` call eh?

     `<img class="rrd"  data-src-template="graphA?start={{start}}&amp;end={{end}}" />`

3.  I believe issue #7's problem is the OP is mistakenly supplying an RRD file name for **graphA** but really, they should have written a server-side application as mentioned above.  Is that right?

Thanks so much!

**Comment by pablos-here** [comment]
Hmmm, I rigged a test and my assumption is wrong, **graphA** seems to be an actual graph.

I'm unclear how to connect the JavaScript with an RRD and how is the image generated.  

I seem to have some fundamental questions.

I'd be grateful for any tips.

Thx!

**Comment by oetiker** [comment]
This project is stable :) for it to work, you need a server which produces graphs as requested by the frontend ... with the JS loaded, your webpage will send requests for different graphs to your backend ...
